import {
  FIELD_WIDTH,
  GAME_CONTAINER_MARGIN_BOTTOM,
  GAME_CONTAINER_MARGIN_TOP,
} from './game/constants'

const HEADER_HEIGHT = 55

export const GAME_CONTAINER_Y = HEADER_HEIGHT + GAME_CONTAINER_MARGIN_TOP

export const GAME_HEIGHT =
  GAME_CONTAINER_Y + FIELD_WIDTH + GAME_CONTAINER_MARGIN_BOTTOM

export { FIELD_WIDTH, HEADER_HEIGHT }
