export const FIELD_WIDTH = 500
export const GRID_SPACING = 15
export const TILE_BORDER_RADIUS = 6
export const GAME_CONTAINER_BORDER_RADIUS = 12
export const GAME_CONTAINER_MARGIN_TOP = 20
export const GAME_CONTAINER_MARGIN_BOTTOM = 40

const HEADER_HEIGHT = 55

export const GAME_CONTAINER_Y = HEADER_HEIGHT + GAME_CONTAINER_MARGIN_TOP

export const GAME_HEIGHT =
  GAME_CONTAINER_Y + FIELD_WIDTH + GAME_CONTAINER_MARGIN_BOTTOM
