import {
  DIGIT_PAD_CONTENT_HEIGHT,
  FIELD_WIDTH,
  GAME_CONTAINER_MARGIN_BOTTOM,
  GAME_CONTAINER_MARGIN_TOP,
  GRID_PADDING,
  STATUS_BAR_HEIGHT,
} from '../game/constants'
import { computeGridPixelSize } from '../gameObjects/gridMetrics'

export const CONTROLS_GAP = 8

export const STATUS_BAR_CENTER_Y = STATUS_BAR_HEIGHT / 2

export const GAME_CONTAINER_Y = STATUS_BAR_HEIGHT + GAME_CONTAINER_MARGIN_TOP

const GRID_BLOCK_HEIGHT = GRID_PADDING * 2 + computeGridPixelSize()

export const DIGIT_PAD_TOP = GAME_CONTAINER_Y + GRID_BLOCK_HEIGHT + CONTROLS_GAP

export const DIGIT_PAD_AREA_HEIGHT =
  DIGIT_PAD_CONTENT_HEIGHT + GAME_CONTAINER_MARGIN_BOTTOM

export const DIGIT_PAD_CENTER_Y = DIGIT_PAD_TOP + DIGIT_PAD_AREA_HEIGHT / 2

export const GAME_HEIGHT = DIGIT_PAD_TOP + DIGIT_PAD_AREA_HEIGHT

export { FIELD_WIDTH }
